<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ43cvzq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ43cvzq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ43cvzq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ43cvzq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ43cvzq\appProdProjectContainer(array(
    'container.build_hash' => 'J43cvzq',
    'container.build_id' => '6bbe70a5',
    'container.build_time' => 1546348202,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ43cvzq');
